# Generated by Django 3.0.11 on 2025-02-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
