# Generated by Django 3.0.11 on 2025-02-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20250215_0537'),
        ('product', '0003_auto_20250215_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='coupon.Coupon'),
        ),
    ]
